[build]
  base = "."
  publish = "."
  command = "echo 'No build required'"
  functions = "netlify/functions"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
